baseurl = "/"
languageCode = "en-US"
title = "Leif Latiff, a Full Stack Engineer"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-110966525-1"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  author = "Leif"
  description = "Full Stack Engineer"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "fishingelephants"
  Email         = "leif.latiff@gmail.com"
  Twitter       = "lee_eep"
  LinkedIn      = "leiflatiff"
  Medium        = "leiflatiff"
  Instagram     = "lee_eep"


